### ISSUE TITLE
Include AWS Tools PS module

### ISSUE THREAD

**Issue by fyopolo** [Buzzcola81/AWS-SSO-KeyHelper#1]
Hi Martin. This is great! I'm wondering if you could please modify it to achieve what I must because I'm not that familiar with the code within.

I'd like to connect to AWS using SSO and MFA but SSO is Azure handled and not ADFS. Another thing I read in your code is it's importing AWSPowerShell module and due it's now deprecated, I'm wondering if updating your script for using AWS Tools module could be an option instead.

Thanks a lot for your contribution!!!!

**Comment by Buzzcola81** [comment]
Thanks for your feedback. I used this tool years ago for my environment and no longer develop it as I found alternative tools have been released since with more functionality and features. Have a look at https://github.com/Versent/saml2aws its multi platform and supports AzureAD along with other identity providers.
